### ISSUE TITLE
How to use integration <class 'scipy.integrate.RK45'>?

### ISSUE THREAD

**Issue by mftatfcyclone** [simupy/simupy#11]
Dear all
I need to change the default integration class of simupy from <class 'scipy.integrate._ode.ode'> to <class 'scipy.integrate.RK45'>. Is it possible?
How?
I tried this, but the code does not work
`result=BD.simulate(10, integrator_class=<class 'scipy.integrate.RK45'>,integrator_options={'t_bound': 10, 'rtol': 1e-06, 'max_step': 1e-4, 'atol': 1e-12})`

**Comment by sixpearls** [comment]
Hi @mftatfcyclone: The `RK45` integration method is not compatible with the old API which SimuPy uses. The default integrator (`scipy.integrate.ode` with the `dopri5` solver) uses the same algorithm as RK45. The only difference is that the implementation SimuPy uses may be faster since it is written in Fortran, rather than pure Python.
